language: python
python:
  - 3.8
services:
  - docker
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - cp .env.travis .env
script:
  - docker-compose build
  - docker-compose run web python manage.py makemigrations gallery
  - docker-compose run web python manage.py migrate
  - docker-compose run web python manage.py test