version: '3'

services:
    redis:
        image: redis
    celery:
        build: .
        command: celery -A imagesearch worker -l info
        volumes:
            - .:/code
        env_file: .env
        depends_on:
          - redis
    celery-beat:
        build: .
        command: celery -A imagesearch beat -l info
        volumes:
            - .:/code
        env_file: .env
        depends_on:
            - redis
    db:
        image: postgres
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        env_file: .env
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis